name: Build Java

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
        - synchronize
        - opened
        - reopened

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: cd tp-api && sh ./gradlew build
