name: Build Java

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
        - synchronize
        - opened
        - reopened

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 3310
          POSTGRES_DB: thirdplace
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        id: gradle_test
        run: | 
          cd tp-api && sh ./gradlew test --info -DDB_BOOTSTRAP_PW=3310 -DDB_DATA_PATH="/usr/local/var/postgreSQL/17/data"
        continue-on-error: true  
      
      - name: Check Test Result
        run: |
          if [ ${{ steps.gradle_test.outcome }} != success ]; then
            echo "TESTS_FAILED=true" >> $GITHUB_ENV
          else
            echo "TESTS_FAILED=false" >> $GITHUB_ENV
          fi 

      - name: Upload test reports
        if: always()  # Ensures this runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: tp-api/build/reports/tests/test/
          retention-days: 2
      
      - name: Fail if tests failed
        if: env.TESTS_FAILED == 'true'
        run: exit 1    
