name: Build Elm

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Elm
        run: |
          npm install -g elm

      - name: Build Elm project
        run: |
          cd tp-frontend && elm make src/Room.elm --output=/dev/null
