name: Build Java

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
        - synchronize
        - opened
        - reopened

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 3310
          POSTGRES_DB: thirdplace
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: cd tp-api && sh ./gradlew build
        continue-on-error: true

      - name: Upload test reports
        if: always()  # Ensures this runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: tp-api/build/reports/tests/test/
          retention-days: 2
