#Akash deployment file
version: "2.0"

services:
  tp-relay:
    image: yourdockerhub/tp-relay:latest
    expose:
      - port: 443
        as: 443
        to:
          - global: true

profiles:
  compute:
    tp-relay:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 256Mi

  placement:
    dcloud:
      pricing:
        tp-relay:
          denom: uakt
          amount: 100 # Adjust this based on market

deployment:
  tp-relay:
    dcloud:
      profile: tp-relay
      count: 1
